stages:
  - build

variables:
  IMAGE_NAME: "sdns-test-gitlab"
  DOCKER_REGISTRY: "registry.gitlab.com"
  DOCKER_TAG_LATEST: "latest"
  DOCKER_IMAGE: "$DOCKER_REGISTRY/ivannajwan22/test1/$IMAGE_NAME"
  DOCKER_BUILDKIT: 1  # Mengaktifkan Docker BuildKit

build_and_push:
  image: docker:latest  # Menggunakan docker:latest
  stage: build
  services:
    - docker:dind  # Menggunakan docker:dind
  before_script:
    # Install git untuk menangani peringatan buildx
    - apk add --no-cache git
    # Debug untuk memastikan `git` tersedia
    - git --version
    # Login ke GitLab Container Registry
    - echo "Logging into GitLab Container Registry..."
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - |
      if [ $? -ne 0 ]; then
        echo "Login failed, exiting pipeline."
        exit 1
      fi
  variables:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
  script:
    # Debug untuk memastikan context
    - echo "Checking current directory..."
    - pwd
    - echo "Listing contents of current directory..."
    - ls -la
    # Tentukan versi image berdasarkan branch/tag
    - echo "Determining version..."
    - VERSION=""
    - |
      if [ "$CI_COMMIT_REF_NAME" == "master" ]; then
        VERSION=$DOCKER_TAG_LATEST
      elif [[ "$CI_COMMIT_TAG" =~ ^v ]]; then
        VERSION=$CI_COMMIT_TAG
      fi
    - |
      if [ -z "$VERSION" ]; then
        echo "Unsupported branch/tag: $CI_COMMIT_REF_NAME"
        exit 1
      fi
    - echo "Building image for version $VERSION..."
    # Siapkan QEMU untuk build multi-arch jika belum tersedia
    - echo "Checking if QEMU is already set up..."
    - docker buildx ls || docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
    # Konfigurasi Docker Buildx
    - echo "Configuring Docker Buildx..."
    - docker buildx use || docker buildx create --use
    - docker buildx inspect --bootstrap
    # Build dan push multi-arch Docker image
    - echo "Starting multi-arch build and push..."
    - |
      docker buildx build \
        --platform linux/arm64,linux/amd64 \
        --push \
        --tag $DOCKER_IMAGE:$VERSION \
        --tag $DOCKER_IMAGE:$DOCKER_TAG_LATEST \
        . || { echo "Docker build or push failed"; exit 1; }
