name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Ganti dengan branch yang sesuai
  pull_request:
    branches:
      - master  # Ganti dengan branch yang sesuai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set timestamp for tag
      run: echo "IMAGE_TAG=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push multi-architecture image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64, linux/arm/v7, linux/amd64, linux/386
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
